```{r}
library(conflicted)
library(pals)
library(ggplot2)
library(ggraph)
library(dplyr)
conflict_prefer("filter", "dplyr")
conflict_prefer("rename", "dplyr")
library(readr)
library(ggrepel)
library(igraph)
library(readxl)
conflicts_prefer(tidygraph::select)
conflicts_prefer(dplyr::count)
library(reshape2)
library(ggplot2)
```


```{r}
primary_tumor_patient_stratification_tumor_cells <- read.csv("/data/projects/2022/CRCA/results/v0.1/crc-atlas-dataset/latest/ds_analyses/liana_cell2cell/neutrophil_subclusters/tumor_blood/neutrophil.csv", row.names=1)
```

```{r}
immune_cells <- c('B cell',
 'DC mature',
 'Macrophage',
 'Mast cell',
 'Monocyte',
 'NK',
 'Neutrophil',
 'Plasma cell',
 'T cell CD4',
 'T cell CD8',
 'T cell regulatory',
 'cDC',
 'pDC','Cancer cell')
```



```{r}
immune_cells_neutro <- c('B cell','Macrophage', 'Monocyte', 'NK',
 'T cell CD4',
 'T cell CD8',
 'T cell regulatory','Cancer cell', 'Neutrophil')
```

## #  How many cell-cell interactions are there between neutrophils and other cell types? 
 
```{r}
tumor_normal_interactions = primary_tumor_patient_stratification_tumor_cells|>
  select(source=source_genesymbol, target=target_genesymbol, fraction_expressed, fdr=fdr, log2_fc=log2FoldChange, cluster_2=cell_type, pvalue) |>
  mutate(group = if_else(log2_fc < 0, "Tumor", "Normal")) |>
  mutate(cluster_1 = 'Neutrophil') |>
  mutate(variable=sprintf("%s_%s_%s_%s", source, target, cluster_1, cluster_2), coef=log2_fc) |>
  filter(cluster_2 %in% c(immune_cells_neutro))


unique_rows <- tumor_normal_interactions[!duplicated(tumor_normal_interactions$variable), ]

```

```{r} 
results <- data.frame(cell_type = character(), number_of_interactions = integer(), stringsAsFactors = FALSE)


# Loop through each cell type in immune_cells_neutro
for (i in immune_cells_neutro) {
  tumor_normal_interactions <- primary_tumor_patient_stratification_tumor_cells %>%
    filter(cell_type == i) %>%
    mutate(
      group = ifelse(log2FoldChange < 0, "Tumor", "Normal"),
      cluster_1 = 'Neutrophil',
      variable = sprintf("%s_%s_%s_%s", source_genesymbol, target_genesymbol, cluster_1, cell_type),
      coef = log2FoldChange
    )
  unique_rows <- tumor_normal_interactions[!duplicated(tumor_normal_interactions$variable), ]
  number_rows <- nrow(unique_rows)
  
  # Append results to the data frame
  results <- rbind(results, data.frame(cell_type = i, number_of_interactions = number_rows, stringsAsFactors = FALSE))
}

results <- results %>%
  rename(source = cell_type,
         neutrophil = number_of_interactions)
```
## How many cell-cell interactions are in total?

```{r}
tumor_normal_interactions = primary_tumor_patient_stratification_tumor_cells|>
  filter(target %in% c(immune_cells_neutro)) |>   mutate(variable=sprintf("%s_%s_%s_%s", source_genesymbol, target_genesymbol, source, target))

unique_sources <- unique(tumor_normal_interactions$target)

unique_rows <- tumor_normal_interactions[!duplicated(tumor_normal_interactions$variable), ]

interaction_matrix <- expand.grid(source = unique_sources, target = unique_sources) %>%
  left_join(unique_rows %>% count(source, target), by = c("source", "target")) %>%
  replace_na(list(n = 0)) %>%
  spread(key = target, value = n, fill = 0)

merged_df <- interaction_matrix %>%
  left_join(results, by = "source")

names(merged_df)[names(merged_df) == "neutrophil"] <- "Neutrophil"


melted_cormat <- melt(interaction_matrix)

# Create the heatmap with labels and renamed axes
p <- ggplot(data = melted_cormat, aes(x = source, y = variable, fill = value)) + 
  geom_tile() +
  geom_text(aes(label = value), color = "black", size = 4) +  # Add numeric labels
  scale_fill_gradient(low = "white", high = "red") +  # Change color scale to reds
  labs(x = "Source", y = "Target", fill = "N.Interactions") +  # Rename x and y axis labels
  theme(axis.text.x = element_text(angle = 45, hjust = 1),   theme_minimal(base_family = "Arial") +  # Clean theme with Arial font
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),  # Adjust x-axis text
        axis.text.y = element_text(size = 12),  # Adjust y-axis text
        axis.title = element_text(size = 14, face = "bold"),  # Adjust axis titles
        legend.title = element_text(size = 14),  # Adjust legend title
        legend.text = element_text(size = 12),  # Adjust legend text
        plot.title = element_text(size = 16, hjust = 0.5, face = "bold"))  # Adjust plot title
)  # Rotate x-axis labels

p
ggsave("all_cells_heatmap_plot.pdf", plot = p, device = "pdf", width = 8, height = 6)

```
 
 
 
```{r}

####
# Convert the numeric dataframe to a matrix
rownames(merged_df) <- merged_df$source
merged_df$source <- NULL
numeric_matrix <- as.matrix(merged_df)

# Sum all the numbers in the matrix
total_sum <- sum(numeric_matrix, na.rm = TRUE)
####
```




```{r}
top_genes = tumor_normal_interactions |> select(source, fdr) |> distinct() |> arrange(fdr) |> pull(source) |> head(10)
```





```{r}
COLORS = list(cell_type=list(
        "B cell"="#1f77b4",
        "Macrophage"="#d62728",
        "Mast cell"="#aa40fc",
        "NK"="#8c564b",
        "Neutrophil"="#e377c2",
        "Plasma cell"="#b5bd61",
        "Monocyte"="#17becf",
        "T cell CD4"="#aec7e8",
        "T cell CD8"="#ff7f0e",
        "T cell regulatory"="#ff4f0e",
        "cDC"="#ffbb78",
        "pDC"="#98df8a",
        "Cancer cell"="#999999"
))
```







```{r}
cpdb_res<- tumor_normal_interactions
```

```{r}
cpdb_res <- cpdb_res |> filter(source %in% top_genes)
```

```{r}
edge_color="log2_fc"
```

```{r}
cell_type_color_scale=COLORS$cell_type
```



```{r}
# make edges df
edges = cpdb_res |>
mutate( from=sprintf("%s_%s_ligand", cluster_1, source), to=sprintf("%s_%s_receptor", cluster_2, target)) |>
select(from, to, name="variable", coef, pvalue, fdr, group, log2_fc) |>
mutate(log2_fc = if_else(is.infinite(log2_fc) & log2_fc < 0, -max(abs(log2_fc[is.finite(log2_fc)])), log2_fc)) |>
mutate(log2_fc = if_else(is.infinite(log2_fc) & log2_fc > 0, max(abs(log2_fc[is.finite(log2_fc)])), log2_fc)) |>
mutate(fdr = if_else(fdr == 0, 1e-255, fdr))
```


```{r}
# make nodes df
nodes_source = cpdb_res |>
  select(cell_type=cluster_1, gene=source) |>
  mutate(type="ligand", fraction_expressed=0.5) |>
  mutate(name=sprintf("%s_%s_%s", cell_type, gene, type))
nodes_target = cpdb_res |>
  select(cell_type=cluster_2, gene=target, fraction_expressed) |>
  mutate(type="receptor") |>
  mutate(name=sprintf("%s_%s_%s", cell_type, gene, type))
nodes = bind_rows(nodes_source, nodes_target) |>
  distinct() |>
  select(name, cell_type, gene, type, fraction_expressed) |>
  filter(name %in% edges$to | name %in% edges$from)

```

```{r}

cell_types = unique(c(cpdb_res$cluster_1, cpdb_res$cluster_2))
cell_type_lr = unique(paste0(nodes$cell_type, "_", nodes$type))

```

```{r}
# construct hierarchy graph for dendrogram
edges_ct_hierarchy = bind_rows(
  # root
  data.frame(from="root", to=nodes$cell_type),
  nodes |> mutate(to=paste0(cell_type, "_", type)) |> select(from=cell_type, to) |> distinct(),
  nodes |> mutate(from=paste0(cell_type, "_", type), to=name) |> select(from, to)
  )
```

```{r}

nodes_ct_hierarchy = data.frame(name=unique(c(edges_ct_hierarchy$to, edges_ct_hierarchy$from))) |>
  left_join(nodes, by="name") |> group_by(cell_type) |>  group_modify(function(x, key) {
    n = nrow(x)
    n1 = floor(n/2)
    n2 = n - 1 - n1
    x$cell_type_label = c(rep(NA, n1), key$cell_type, rep(NA, n2))
    x
  }) |> ungroup() |> select(name, cell_type, gene, type, cell_type_label, fraction_expressed)
G_ct =graph_from_data_frame(edges_ct_hierarchy, directed=TRUE, vertices=nodes_ct_hierarchy)
```

```{r}
# info for geom_conn_bundle
from = match(edges$from, nodes_ct_hierarchy$name)
to = match(edges$to, nodes_ct_hierarchy$name)
conn_meta = data.frame(from=nodes_ct_hierarchy[from,]$name, to=nodes_ct_hierarchy[to,]$name) |>
  left_join(edges, by=c("from", "to"))
```
```{r}
edge_color_scale=scale_edge_color_gradientn(colors=pals::coolwarm(100), limits=c(-1.5,1.5) * max(abs(conn_meta[[edge_color]])))
```



```{r}
# plot using ggraph

p = ggraph(G_ct, layout="dendrogram", circular=TRUE) +
  geom_node_point(aes(color=cell_type, shape=type, size=fraction_expressed), stroke=2, fill="white") +
  geom_conn_bundle(
    data = get_con(from=from, to=to, coef=conn_meta$coef, log2_fc=conn_meta$log2_fc, pvalue=conn_meta$pvalue, group=conn_meta$group, fdr=conn_meta$fdr),
    # aes_string(color=edge_color, width="abs(coef)"),
    aes_string(color=edge_color, width="abs(log10(fdr))"),
    tension=0.4,
    arrow=arrow()) +
  edge_color_scale +
  scale_edge_width_continuous(range=c(0.5,2)) +
  theme_void() +
  geom_text_repel(aes(x=x, y=y, label=gene), size=7 ) +
  geom_label_repel(aes(x=x, y=y, nudge_x=1.2*x, nudge_y=1.3*y, label=cell_type_label), xlim=c(-2, 2), size=10, force=3, alpha=.8) +
  coord_fixed(clip="off") +
  scale_shape_manual(values=c("receptor"=19, "ligand"=21))  +
  scale_color_manual(values=cell_type_color_scale)   +
  scale_size_continuous(range=c(2, 14)) +
 theme(legend.position="bottom",legend.margin = margin(t = 1.5, unit = "cm"),legend.key.size = unit(0.8, "cm"), plot.margin = margin(2, 3, 3, 3, "cm"),
        plot.title = element_text(size = 20, margin = margin(b = 1, unit = "cm"), hjust = 0.5)) +  # Center align the title

  #ggtitle("Crosstalk of Cancer cell with major immune cells in tumor vs normal. Top 10 DEG in Cancer cell")
  ggtitle("prueba")
p



#ggsave("circos_plot_core_atlas_tumor_normal.pdf", plot = p, width = 55, height = 45, units = "cm")
ggsave("prueba.pdf", plot = p, width = 55, height = 45, units = "cm")
```